services:
  # Main Vendure Server
  - type: web
    name: younique-india-server
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_ENV
        value: production
      - key: PORT
        value: 10000
      - key: COOKIE_SECRET
        fromService:
          type: web
          name: younique-india-server
          envVarKey: COOKIE_SECRET
      - key: SUPERADMIN_USERNAME
        fromService:
          type: web
          name: younique-india-server
          envVarKey: SUPERADMIN_USERNAME
      - key: SUPERADMIN_PASSWORD
        fromService:
          type: web
          name: younique-india-server
          envVarKey: SUPERADMIN_PASSWORD
      - key: DB_HOST
        fromService:
          type: web
          name: younique-india-server
          envVarKey: DB_HOST
      - key: DB_PORT
        fromService:
          type: web
          name: younique-india-server
          envVarKey: DB_PORT
      - key: DB_NAME
        fromService:
          type: web
          name: younique-india-server
          envVarKey: DB_NAME
      - key: DB_USERNAME
        fromService:
          type: web
          name: younique-india-server
          envVarKey: DB_USERNAME
      - key: DB_PASSWORD
        fromService:
          type: web
          name: younique-india-server
          envVarKey: DB_PASSWORD
      - key: DB_SCHEMA
        fromService:
          type: web
          name: younique-india-server
          envVarKey: DB_SCHEMA
      - key: DB_SSL
        fromService:
          type: web
          name: younique-india-server
          envVarKey: DB_SSL

  # Vendure Worker (Background Jobs)
  - type: worker
    name: younique-india-worker
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start:worker
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_ENV
        value: production
      - key: COOKIE_SECRET
        fromService:
          type: web
          name: younique-india-server
          envVarKey: COOKIE_SECRET
      - key: SUPERADMIN_USERNAME
        fromService:
          type: web
          name: younique-india-server
          envVarKey: SUPERADMIN_USERNAME
      - key: SUPERADMIN_PASSWORD
        fromService:
          type: web
          name: younique-india-server
          envVarKey: SUPERADMIN_PASSWORD
      - key: DB_HOST
        fromService:
          type: web
          name: younique-india-server
          envVarKey: DB_HOST
      - key: DB_PORT
        fromService:
          type: web
          name: younique-india-server
          envVarKey: DB_PORT
      - key: DB_NAME
        fromService:
          type: web
          name: younique-india-server
          envVarKey: DB_NAME
      - key: DB_USERNAME
        fromService:
          type: web
          name: younique-india-server
          envVarKey: DB_USERNAME
      - key: DB_PASSWORD
        fromService:
          type: web
          name: younique-india-server
          envVarKey: DB_PASSWORD
      - key: DB_SCHEMA
        fromService:
          type: web
          name: younique-india-server
          envVarKey: DB_SCHEMA
      - key: DB_SSL
        fromService:
          type: web
          name: younique-india-server
          envVarKey: DB_SSL
